[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_SUPABASE_URL = "https://ovmyaouiskbsbxyezijx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_IxAkYaPuksJQYoQDA_pv7GpjIz"

[functions]
  directory = "netlify/functions"

[functions."*"]
  timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
